follow symlink
kmc-jp/rubwiki2 pull request #9
Opened 2019-04-09 05:52 UTC by nna774

2019-04-09 06:06 UTC, nna774 commented
https://github.com/kmc-jp/rubwiki2/blob/ba5ab6ecffe54e18aa5415fd3b94b144c48b2f23/lib/git.rb#L151 ここで通常のファイルに戻ってしまってる気がする。

2019-04-09 07:03 UTC, nna774 commented
多分動く気がするのでデプロイしてみた。
多分動いてる。

2019-04-09 07:06 UTC, nna774 commented
https://inside.kmc.gr.jp/rubwiki/sandbox
https://inside.kmc.gr.jp/rubwiki/sandboxes/sandbox
とかが おすなば に飛べば嬉しい。

2019-04-09 15:33 UTC, nonylene requested changes

2019-04-09 15:33 UTC, nonylene commented on lib/git.rb
> +        return Blob.new(@repo, oid, obj[:filemode])
検索するとこの行でエラーになる

```
NoMethodError - undefined method `[]' for #<Rugged::Blob:0x00007f83ec592a78>:
```

原因は以下？

1. `@repo.lookup` で Blob が返ってきている
2. しかし、 `:filemode` は Tree 以下の entry にあって、 Blob には存在しないのでエラーになる
    - https://github.com/kmc-jp/rubwiki2/pull/9/files#diff-3358f1978caa04bed52188edf55c88a3R176 は Tree の各 entry を each してるので正しい。

2019-04-10 15:51 UTC, nonylene commented on lib/git.rb
> +        return Blob.new(@repo, oid, obj[:filemode])
f720769

2019-04-10 15:56 UTC, nonylene approved these changes

2019-04-11 10:29 UTC, nna774 commented
マジでマージしていですか。

2019-04-11 10:30 UTC, nonylene commented
ディレクトリ、非対応ということで消していいのでは

2019-04-11 10:41 UTC, nonylene commented
動くなら良さそう

2019-04-11 10:41 UTC, merged